### ISSUE TITLE
issue requiring 'postcss-middleware'

### ISSUE THREAD

**Issue by m4tta** [jedmao/postcss-middleware#7]
Using just the basic examples provided in the readme

``` js
var postcssMiddleware = require('postcss-middleware');

const express = require('express');
const app = express();
app.use('/css', postcssMiddleware(/* options */));
```

I get "postcssMiddleware" is not a function on this line:

``` js
app.use('/css', postcssMiddleware(/* options */));
```

After some quick toying around I notice the require statement is returning:

``` js
{ default: [Function: PostCssMiddleware] }
```

So I changed my require statement to look like this:

``` js
var postcssMiddleware = require('postcss-middleware').default;
```

This makes everything work fine. Am I doing something wrong, misunderstanding or is the readme outdated?

I am using latest NodeJs 6.x.x and Latest NPM.

**Comment by jednano** [comment]
You're not doing anything wrong. I've had similar issues with other projects after upgrading the TypeScript compiler and I think the issue here is simply my ignorance. I'm just not sure how to configure TypeScript to compile this correctly or if there's a way to do it at all. We have the same issue with the TypeScript definitions for postcss and I don't yet have a solution.

**Comment by m4tta** [comment]
That's fine I suppose. Everything works great. Does postcss-middleware do any caching or does each request recompile the css? I couldn't find anything that clearly answered that from the source.

**Comment by jednano** [comment]
There are no caching features ATM.

**Comment by Xiphe** [comment]
Had the same issue seems to be introduced by e5207c53d9db379601d8ad733f1bd3c02a46c91d which should have been considered as a breaking change and be released as `v2.0.0` instead of `v1.1.1`

**Comment by jednano** [comment]
@Xiphe it wasn't intended to be a breaking change, because this is a bug. This should now be fixed in v1.1.2.

**Comment by Xiphe** [comment]
good to know. thanks for the explanation and keep up the great work 👍
